import { Injectable } from "@angular/core";
import {
  AngularFirestore,
  AngularFirestoreCollection,
  AngularFirestoreDocument
} from "angularfire2/firestore";
import { Observable } from "rxjs";
import { map } from "rxjs/operators";
import { Client } from "../models/Client";

@Injectable({
  providedIn: "root"
})
export class ClientService {
  clientsCollection: AngularFirestoreCollection<Client>;
  clientDoc: AngularFirestoreDocument<Client>;
  clients: Observable<Client[]>;
  client: Observable<Client>;

  constructor(private afs: AngularFirestore) {
    this.clientsCollection = this.afs.collection("clients", (ref) =>
      ref.orderBy("lastName", "asc")
    );
  }

  getClients(): Observable<Client[]> {
    this.clients = this.clientsCollection.snapshotChanges().pipe(
      map((changes) => {
        return changes.map((action) => {
          const client = action.payload.doc.data() as Client;
          client.id = action.payload.doc.id;

          // TODO remove soon: temporary code to remove legacy property likescount and add new prop likes
          if (client.likesCount) {
            delete client.likesCount;
          }
          if (!client.likes) {
            client.likes = [];
          }
          this.updateClient(client);

          return client;
        });
      })
    );
    return this.clients;
  }


  /** GET CLIENT, ADD ID MANUALLY
   * if no id needed can use valueChanges
   * get actions with payload whose data will be a client
   * manually add id to client and return it
   *
   * ACTIONS API = {type: ie value, payload: }
   */
  getClient(id: string): Observable<Client> {
    this.clientDoc = this.afs.doc<Client>(`clients/${id}`);
    this.client = this.clientDoc.snapshotChanges().pipe(
      map((action) => {
        // action is a DocumentSnapshot w/ props: payload.exists: boolean, payload.id, proto.fields (client props/fields)
        if (action.payload.exists === false) {
          console.log("action w NO payload", action);
          return null;
        } else {
          console.log("action w payload", action.payload);
          const data = action.payload.data() as Client;
          data.id = action.payload.id;
          return data;
        }
      })
    );
    return this.client;
  }

  // use .add when you want an id generated by firestore
  // https://firebase.google.com/docs/firestore/manage-data/add-data
  newClient(client: Client) {
    this.clientsCollection.add(client).then((docRef) => {
      console.log("added to this docRef", docRef);
    });
  }

  updateClient(client: Client) {
    this.clientDoc = this.afs.doc<Client>(`clients/${client.id}`);
    this.clientDoc.update(client);
  }

  deleteClient(client: Client) {
    console.log(client);
    this.clientDoc = this.afs.doc<Client>(`clients/${client.id}`);
    this.clientDoc.delete();
  }
} // end class
